repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: check-added-large-files
            args: ['--maxkb=2000']
          - id: check-yaml
            args: ['--allow-multiple-documents']
          - id: check-json
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: check-merge-conflict
    - repo: https://github.com/biomejs/pre-commit
      rev: v2.5.12
      hooks:
          - id: biome-check
            additional_dependencies: ['@biomejs/biome@2.5.12']
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.30.0
      hooks:
          - id: gitleaks
